"""baseline schema

Revision ID: 886c73dc9e58
Revises: 
Create Date: 2026-06-07 00:16:48.014574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.time import UTCDateTime


# revision identifiers, used by Alembic.
revision: str = '886c73dc9e58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('live_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('theme_id', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('current_q_idx', sa.Integer(), nullable=False),
    sa.Column('question_started_at', UTCDateTime(), nullable=True),
    sa.Column('question_duration_s', sa.Integer(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('question_order', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('live_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_sessions_state'), ['state'], unique=False)

    op.create_table('users',
    sa.Column('pseudo', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_seed', sa.String(length=32), nullable=False),
    sa.Column('bio', sa.String(length=200), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('banned', sa.Boolean(), nullable=False),
    sa.Column('custom_avatar_filename', sa.String(length=80), nullable=True),
    sa.Column('custom_avatar_status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('pseudo')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_custom_avatar_status'), ['custom_avatar_status'], unique=False)

    op.create_table('badge_unlocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pseudo', sa.String(length=20), nullable=False),
    sa.Column('badge_id', sa.String(length=50), nullable=False),
    sa.Column('unlocked_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pseudo'], ['users.pseudo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('badge_unlocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_badge_unlocks_badge_id'), ['badge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_badge_unlocks_pseudo'), ['pseudo'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pseudo', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('ts', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pseudo'], ['users.pseudo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_pseudo'), ['pseudo'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_ts'), ['ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_type'), ['type'], unique=False)

    op.create_table('live_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('pseudo', sa.String(length=20), nullable=False),
    sa.Column('q_id', sa.String(length=80), nullable=False),
    sa.Column('choice', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('ts', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pseudo'], ['users.pseudo'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'pseudo', 'q_id', name='uq_lanswer_sid_pseudo_qid')
    )
    with op.batch_alter_table('live_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_answers_pseudo'), ['pseudo'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_answers_q_id'), ['q_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_answers_session_id'), ['session_id'], unique=False)

    op.create_table('live_participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('pseudo', sa.String(length=20), nullable=False),
    sa.Column('avatar_seed', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('joined_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pseudo'], ['users.pseudo'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'pseudo', name='uq_lparticipant_sid_pseudo')
    )
    with op.batch_alter_table('live_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_live_participants_pseudo'), ['pseudo'], unique=False)
        batch_op.create_index(batch_op.f('ix_live_participants_session_id'), ['session_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pseudo', sa.String(length=20), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('ts', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.Column('discord_message_id', sa.String(length=40), nullable=True),
    sa.Column('discord_thread_id', sa.String(length=40), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('flagged_reason', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['pseudo'], ['users.pseudo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_flagged'), ['flagged'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_pseudo'), ['pseudo'], unique=False)

    op.create_table('votes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pseudo', sa.String(length=20), nullable=False),
    sa.Column('topic_id', sa.String(length=50), nullable=False),
    sa.Column('ts', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pseudo'], ['users.pseudo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_votes_pseudo'), ['pseudo'], unique=False)
        batch_op.create_index(batch_op.f('ix_votes_topic_id'), ['topic_id'], unique=False)

    op.create_table('question_reactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('pseudo', sa.String(length=20), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=False),
    sa.Column('ts', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pseudo'], ['users.pseudo'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'pseudo', 'emoji', name='uq_qreact_qid_pseudo_emoji')
    )
    with op.batch_alter_table('question_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_reactions_emoji'), ['emoji'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_reactions_pseudo'), ['pseudo'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_reactions_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_reactions_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_reactions_pseudo'))
        batch_op.drop_index(batch_op.f('ix_question_reactions_emoji'))

    op.drop_table('question_reactions')
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_votes_topic_id'))
        batch_op.drop_index(batch_op.f('ix_votes_pseudo'))

    op.drop_table('votes')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_pseudo'))
        batch_op.drop_index(batch_op.f('ix_questions_flagged'))

    op.drop_table('questions')
    with op.batch_alter_table('live_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_participants_session_id'))
        batch_op.drop_index(batch_op.f('ix_live_participants_pseudo'))

    op.drop_table('live_participants')
    with op.batch_alter_table('live_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_answers_session_id'))
        batch_op.drop_index(batch_op.f('ix_live_answers_q_id'))
        batch_op.drop_index(batch_op.f('ix_live_answers_pseudo'))

    op.drop_table('live_answers')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_type'))
        batch_op.drop_index(batch_op.f('ix_events_ts'))
        batch_op.drop_index(batch_op.f('ix_events_pseudo'))

    op.drop_table('events')
    with op.batch_alter_table('badge_unlocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_badge_unlocks_pseudo'))
        batch_op.drop_index(batch_op.f('ix_badge_unlocks_badge_id'))

    op.drop_table('badge_unlocks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_custom_avatar_status'))

    op.drop_table('users')
    with op.batch_alter_table('live_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_live_sessions_state'))

    op.drop_table('live_sessions')
    op.drop_table('app_state')
    # ### end Alembic commands ###
