"""Quiz catalog — 6 thèmes × 5 questions.

Stocké en code (pas en DB) pour rester versionné et facilement éditable
avant chaque session. À relire/ajuster par l'intervenant.

Format de chaque question :
  id          : identifiant stable (utilisé dans les events)
  prompt      : énoncé
  choices     : 4 options dans l'ordre A, B, C, D
  answer      : index 0..3 de la bonne réponse
  explanation : 1-2 phrases affichées après la soumission
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Question:
    id: str
    prompt: str
    choices: tuple[str, str, str, str]
    answer: int
    explanation: str


@dataclass(frozen=True)
class Theme:
    id: str
    label: str
    emoji: str
    questions: tuple[Question, ...]


VOCAB = Theme(
    id="vocab", label="Vocabulaire de base", emoji="🔤",
    questions=(
        Question("vocab-cpu",
            "Que veut dire CPU ?",
            ("Central Processing Unit", "Central Power Unit", "Computer Processing Unit", "Core Performance Unit"),
            0,
            "Le CPU est le « cerveau » qui exécute les instructions. La bonne traduction : Central Processing Unit."),
        Question("vocab-ram",
            "À quoi sert la RAM ?",
            ("Stocker des fichiers de façon permanente",
             "Garder les données actives à portée du CPU",
             "Refroidir activement le processeur central",
             "Servir d'antenne pour la connexion internet"),
            1,
            "La RAM est rapide mais volatile : elle perd ses données quand on éteint la machine."),
        Question("vocab-ip",
            "Qu'est-ce qu'une adresse IP ?",
            ("L'identifiant physique d'une carte réseau",
             "L'adresse qui localise un appareil sur un réseau",
             "Le mot de passe par défaut d'une box internet",
             "Le nom de domaine lisible d'un site web"),
            1,
            "L'IP localise un appareil sur le réseau (ex: 192.168.1.42 sur ton wifi maison). Elle n'est pas figée : ta box t'en attribue une dynamiquement via DHCP, et ton IP publique peut changer aussi. À ne pas confondre avec l'adresse MAC, qui identifie physiquement la carte réseau."),
        Question("vocab-units",
            "Quelle unité est la plus grande ?",
            ("1 Gigaoctet (Go)", "1 Téraoctet (To)", "1 Mégaoctet (Mo)", "1 Kilooctet (Ko)"),
            1,
            "Ordre croissant : Ko < Mo < Go < To. 1 To ≈ 1000 Go ≈ 1 million de Mo."),
        Question("vocab-ssd",
            "C'est quoi un SSD ?",
            ("Un écran haute définition pour ordi portable",
             "Une mémoire de stockage sans pièce mécanique",
             "Une protection antivirus matérielle moderne",
             "Un port USB de transfert ultra-rapide"),
            1,
            "Solid State Drive — pas de plateaux qui tournent, donc accès quasi instantané."),
        Question("vocab-os",
            "C'est quoi un système d'exploitation (OS) ?",
            ("Un antivirus intégré directement à l'ordinateur",
             "Le logiciel-pivot entre matériel et applications",
             "Une marque réputée de processeur grand public",
             "Le navigateur web par défaut livré avec l'ordi"),
            1,
            "Windows, macOS, Linux, Android, iOS. L'OS gère mémoire, fichiers, processus, et expose des APIs aux applis."),
        Question("vocab-wifi-eth",
            "Quelle différence principale entre WiFi et Ethernet ?",
            ("Ethernet est plus lent que le WiFi en pratique",
             "WiFi passe par ondes radio, Ethernet par câble",
             "Le WiFi ne marche qu'à la maison, jamais ailleurs",
             "Ethernet n'existe qu'en entreprise et data center"),
            1,
            "Le câble Ethernet offre moins de latence et plus de débit stable. Le WiFi est pratique mais sensible aux interférences."),
        Question("vocab-cache-cpu",
            "À quoi sert la mémoire cache d'un CPU ?",
            ("À sauvegarder les fichiers de l'utilisateur",
             "À garder les données chaudes près du CPU",
             "À refroidir physiquement le processeur central",
             "À stocker les emails reçus dans le navigateur"),
            1,
            "Hiérarchie : registres → L1 → L2 → L3 → RAM → SSD. Plus on monte, plus c'est rapide mais petit."),
        Question("vocab-pixel",
            "Un pixel, c'est quoi ?",
            ("Une unité de mesure de l'intensité sonore",
             "Un point lumineux élémentaire d'une image",
             "Un virus informatique qui pixellise les écrans",
             "Un format de fichier image vectoriel récent"),
            1,
            "Pixel = « picture element ». Un écran Full HD = 1920 × 1080 = ~2 millions de pixels. Chaque pixel a 3 sous-pixels (R/V/B)."),
        Question("vocab-usbc",
            "L'USB-C, c'est :",
            ("Une nouvelle norme de WiFi public sécurisé",
             "Un connecteur réversible data + vidéo + alim",
             "Un antivirus matériel monté en USB externe",
             "Une marque de smartphone milieu de gamme"),
            1,
            "Depuis 2024, obligatoire dans l'UE pour les smartphones, tablettes, etc. Un seul câble pour tout charger : grosse simplification."),
    ),
)

CYBER = Theme(
    id="cyber", label="Cyber", emoji="🛡️",
    questions=(
        Question("cyber-phishing",
            "Qu'est-ce qu'un phishing ?",
            ("Un type de virus qui infecte les fichiers",
             "Un faux message pour voler tes identifiants",
             "Un mot de passe trop court à la création",
             "Une attaque qui sature un serveur cible"),
            1,
            "Phishing = hameçonnage. Toujours vérifier l'URL et l'expéditeur avant de cliquer."),
        Question("cyber-ransomware",
            "Un ransomware, c'est quoi ?",
            ("Un logiciel commercial gratuit grand public",
             "Un malware qui chiffre tes fichiers contre rançon",
             "Un programme qui mine de la crypto en arrière-plan",
             "Un bot qui répond aux mails à la place de toi"),
            1,
            "Ne jamais payer la rançon : aucune garantie de récupération, et ça finance les pirates."),
        Question("cyber-2fa",
            "Qu'est-ce que le 2FA (authentification à deux facteurs) ?",
            ("Avoir deux mots de passe différents par compte",
             "Un 2ᵉ élément en plus du mot de passe au login",
             "Se connecter depuis deux appareils en même temps",
             "Utiliser un VPN pour masquer son trafic réseau"),
            1,
            "Même si ton mot de passe fuit, l'attaquant ne peut pas se connecter sans ton deuxième facteur."),
        Question("cyber-pwd-manager",
            "Qu'est-ce qu'un gestionnaire de mots de passe ?",
            ("Un site qui génère un mdp aléatoire à la volée",
             "Un logiciel qui stocke et remplit tes mdp chiffrés",
             "Une feuille papier où tu notes tes mdp à la main",
             "Une fonctionnalité système exclusive à Windows"),
            1,
            "Bitwarden, KeePass, 1Password... Permet d'avoir un mdp unique et fort par site, sans avoir à les retenir."),
        Question("cyber-vector",
            "Quelle est la principale faille exploitée par les rançongiciels ?",
            ("Une faille matérielle dans le CPU lui-même",
             "L'utilisateur qui clique sur un lien malveillant",
             "La vitesse trop élevée de la connexion internet",
             "Une mauvaise marque d'antivirus chez la cible"),
            1,
            "L'erreur humaine reste le vecteur n°1. D'où l'importance de la sensibilisation et de la prudence avec les mails."),
        Question("cyber-pwd-strength",
            "Qu'est-ce qui rend un mot de passe vraiment fort ?",
            ("Beaucoup de caractères spéciaux même s'il est court",
             "Sa longueur — une passphrase de 4-5 mots aléatoires",
             "Le fait qu'il contienne ta date de naissance complète",
             "Qu'il commence par une majuscule et finisse par un !"),
            1,
            "L'entropie dépend surtout de la longueur. « cheval-vinyle-cactus-orage » est plus solide que « P@ss1! »."),
        Question("cyber-vpn",
            "À quoi sert un VPN ?",
            ("À naviguer plus rapidement sur internet partout",
             "À chiffrer ton trafic via un serveur tiers",
             "À supprimer les pubs vidéo sur les sites de stream",
             "À débloquer Netflix dans les pays bridés gratuit"),
            1,
            "Un VPN protège sur wifi public et masque ton IP, mais ne te rend pas anonyme. L'opérateur du VPN voit tout."),
        Question("cyber-backup-321",
            "Quelle est la règle de backup « 3-2-1 » ?",
            ("3 disques durs, 2 SSD, 1 cloud public payant",
             "3 copies sur 2 supports différents, 1 hors site",
             "3 utilisateurs, 2 mots de passe, 1 admin du SI",
             "3 antivirus, 2 firewalls, 1 système IDS actif"),
            1,
            "Stratégie classique : 1 copie de prod + 1 sauvegarde locale (NAS) + 1 sauvegarde distante (cloud / autre site). Survivre à un crash, un ransomware, un incendie."),
        Question("cyber-updates",
            "Pourquoi faire les mises à jour de sécurité ?",
            ("Pour avoir les nouvelles fonctionnalités cool",
             "Pour patcher les failles déjà exploitées en live",
             "Pour libérer un peu d'espace sur le disque dur",
             "Inutile dès qu'un antivirus est installé chez toi"),
            1,
            "Les attaquants scannent en masse à la recherche d'appareils non à jour. Beaucoup d'attaques utilisent des failles patchées depuis des mois."),
        Question("cyber-social-eng",
            "L'ingénierie sociale, c'est :",
            ("Construire des réseaux sociaux pour entreprises",
             "Manipuler une personne pour qu'elle révèle un secret",
             "Une théorie sociologique sur les usages d'internet",
             "Une méthode de pentest dédiée aux switches réseau"),
            1,
            "L'humain est souvent le maillon faible. Faux supports techniques, faux livreurs, faux RH : les attaquants exploitent la confiance et l'urgence."),
    ),
)

DEV = Theme(
    id="dev", label="Code & dev", emoji="💻",
    questions=(
        Question("dev-bug",
            "Qu'est-ce qu'un « bug » dans un programme ?",
            ("Un insecte qui rentre dans le boîtier du PC",
             "Un comportement non désiré du code à l'exécution",
             "Un virus informatique de propagation rapide",
             "Un type de fichier généré par le compilateur"),
            1,
            "Le mot vient d'un vrai papillon de nuit coincé dans un relais en 1947, mais aujourd'hui c'est métaphorique."),
        Question("dev-api",
            "C'est quoi une API ?",
            ("Une application mobile native installée",
             "Une interface entre deux logiciels qui causent",
             "Un type de batterie pour serveur rack 1U",
             "Un programme antivirus commercial moderne"),
            1,
            "Application Programming Interface. Quand ton appli météo affiche les températures, elle appelle une API."),
        Question("dev-commit",
            "Qu'est-ce qu'un commit dans Git ?",
            ("Un message broadcast à toute l'équipe dev",
             "Un instantané du code avec un message texte",
             "Une erreur de syntaxe détectée au build",
             "Le fait de publier un site web en production"),
            1,
            "Chaque commit a un hash unique. Tu peux revenir à n'importe quel commit du passé."),
        Question("dev-opensource",
            "Open source veut dire :",
            ("Le logiciel est forcément gratuit pour tout le monde",
             "Le code source est public, lisible et modifiable",
             "Le logiciel est dangereux parce que non sécurisé",
             "Le logiciel ne fonctionne que sur la distrib Linux"),
            1,
            "Gratuit ≠ libre. Un open source peut être payant ; un gratuit peut être propriétaire fermé."),
        Question("dev-js",
            "Quel langage est utilisé côté navigateur pour rendre une page interactive ?",
            ("Python (Django)", "JavaScript", "Java (Spring)", "SQL (BDD)"),
            1,
            "JavaScript ≠ Java (rien à voir malgré le nom). Tourne dans tous les navigateurs modernes."),
        Question("dev-compiled-interpreted",
            "Différence entre langage compilé et interprété ?",
            ("Les compilés sont plus jolis à lire que les autres",
             "Compilé = traduit en machine ; interprété = lu en live",
             "Compilé pour Windows, interprété pour Linux uniquement",
             "C'est exactement la même chose en pratique aujourd'hui"),
            1,
            "Compilés : C, Rust, Go. Interprétés : Python, JS, Ruby. Beaucoup mixent (JIT) : Java, C#, JavaScript moderne."),
        Question("dev-refactor",
            "Qu'est-ce que le refactoring ?",
            ("Réécrire le projet entier complètement de zéro",
             "Améliorer la structure du code sans changer le comportement",
             "Ajouter de nouvelles features visibles côté utilisateur",
             "Supprimer les commentaires devenus obsolètes du code"),
            1,
            "Refactor = nettoyer en gardant le même comportement. Les tests doivent passer avant ET après."),
        Question("dev-unit-test",
            "À quoi sert un test unitaire ?",
            ("À vérifier qu'une fonction fait son boulot en isolation",
             "À tester toute l'application en un seul gros run lent",
             "À surveiller si le serveur de prod tourne bien live",
             "À comparer les performances de deux PCs en benchmark"),
            0,
            "Un test unitaire est petit, rapide, et teste UNE chose précise. Une vraie suite peut avoir des milliers."),
        Question("dev-pr",
            "C'est quoi une « pull request » (PR) / « merge request » (MR) ?",
            ("Une demande candidature pour devenir développeur",
             "Une proposition d'intégrer un changement, mise en revue",
             "Un message d'erreur affiché quand un commit échoue",
             "Une commande Git pour télécharger un repo complet"),
            1,
            "Le workflow standard : tu codes sur une branche, tu pousses, tu ouvres une PR, les collègues review, ça merge."),
        Question("dev-doc",
            "Lire la doc avant de coder, c'est :",
            ("Une perte de temps, mieux vaut apprendre en codant",
             "Un réflexe pro essentiel pour gagner du temps",
             "Une étape réservée aux débutants en programmation",
             "Inutile dès qu'on a accès à ChatGPT ou un LLM"),
            1,
            "« Read The Fucking Manual » (RTFM) est un classique. La doc officielle d'une lib bat 9 fois sur 10 un tuto YouTube périmé."),
    ),
)

NETWORK = Theme(
    id="reseau", label="Réseau", emoji="🌐",
    questions=(
        Question("net-https",
            "Quelle est la différence entre HTTP et HTTPS ?",
            ("HTTPS est plus rapide que HTTP en pratique",
             "HTTPS chiffre les échanges entre client et serveur",
             "HTTP est réservé aux sites web payants exclusifs",
             "HTTPS ne fonctionne pas sur mobile correctement"),
            1,
            "Sans HTTPS, n'importe qui sur le même wifi peut lire tes requêtes en clair."),
        Question("net-url-ip",
            "Une URL et une adresse IP, c'est pareil ?",
            ("Oui : deux noms différents pour la même chose",
             "Non : l'URL est lisible, l'IP est un numéro",
             "Non : l'URL est mondiale, l'IP est sur ton wifi",
             "L'URL est obsolète, on n'utilise plus que l'IP"),
            1,
            "lycee.nebulahost.tech → DNS → 78.46.x.y → contact serveur. Le DNS est l'annuaire intermédiaire."),
        Question("net-dns",
            "À quoi sert le DNS ?",
            ("À sécuriser un site avec un certificat TLS",
             "À traduire un nom de domaine en adresse IP",
             "À héberger les emails entrants d'un domaine",
             "À détecter les virus dans les téléchargements"),
            1,
            "Domain Name System. L'annuaire du web : tu lui demandes « c'est quoi l'IP de google.com ? », il te la donne."),
        Question("net-lan",
            "Que veut dire LAN ?",
            ("Linux Adapter Network",
             "Local Area Network",
             "Long Adapter Network",
             "Limited Access Network"),
            1,
            "Réseau local (ton wifi maison). À distinguer du WAN (Wide Area Network = internet)."),
        Question("net-443",
            "Pourquoi le port 443 est important ?",
            ("C'est le port standard du HTTPS sur le web",
             "C'est le port utilisé pour jouer en multijoueur",
             "C'est le port qui sert à recevoir les emails",
             "C'est le port réservé aux antennes 5G mobiles"),
            0,
            "Port 80 = HTTP (clair), port 443 = HTTPS (chiffré). Quand tu vas sur un site web, tu tapes implicitement sur :443."),
        Question("net-bandwidth-latency",
            "Bande passante vs latence : quelle différence ?",
            ("Aucune, les deux termes sont synonymes",
             "Bande = débit max ; latence = délai aller-retour",
             "La latence compte moins que la bande passante toujours",
             "La bande passante n'existe qu'avec la fibre optique"),
            1,
            "Pour streamer une 4K : bande passante. Pour jouer en ligne sans lag : latence (ping faible). Les deux comptent pour des usages différents."),
        Question("net-nat",
            "À quoi sert le NAT (Network Address Translation) ?",
            ("À traduire automatiquement l'anglais en français",
             "À partager une seule IP publique entre plusieurs appareils",
             "À cacher complètement ton IP au fournisseur d'accès",
             "À accélérer la vitesse du wifi domestique de la box"),
            1,
            "Sans NAT, on aurait épuisé les adresses IPv4 depuis longtemps. Ta box garde la correspondance entre tes IPs locales (192.168.x.x) et l'IP publique."),
        Question("net-cookies",
            "À quoi servent les cookies de navigateur ?",
            ("À stocker des recettes culinaires en favoris",
             "À garder un état (session, préférences) entre pages",
             "À accélérer les téléchargements de gros fichiers",
             "À enregistrer la musique des sites de streaming"),
            1,
            "Cookies de session = te garder connecté. Cookies tiers = te traquer entre sites. Le RGPD impose le consentement pour ces derniers."),
        Question("net-ping",
            "Que mesure un « ping » ?",
            ("Le débit max en MB/s de ta connexion",
             "Le temps aller-retour d'un paquet en ms",
             "Le nombre de connexions ouvertes simultanées",
             "L'âge du serveur depuis son installation"),
            1,
            "Un ping de 20ms est très bon. 100ms passable. 300ms+ = jeu en ligne désagréable. La distance physique et la qualité du réseau jouent."),
        Question("net-dhcp",
            "Quand tu te connectes à un wifi, qui te donne ton IP ?",
            ("Ton fournisseur d'accès internet directement",
             "Le serveur DHCP de ta box, automatiquement",
             "Tu dois la saisir toi-même à la connexion",
             "Google ou Cloudflare pour les wifi domestiques"),
            1,
            "DHCP (Dynamic Host Configuration Protocol) attribue dynamiquement IP, masque, passerelle, DNS. Bail typique : quelques heures à plusieurs jours."),
    ),
)

IA = Theme(
    id="ia", label="Intelligence artificielle", emoji="🧠",
    questions=(
        Question("ia-llm",
            "Que veut dire LLM ?",
            ("Local Language Machine",
             "Large Language Model",
             "Logic Learning Machine",
             "Long Logical Memory"),
            1,
            "ChatGPT, Claude, Mistral, LLaMA sont des LLM. Ils prédisent statistiquement le mot suivant."),
        Question("ia-hallucination",
            "Pourquoi un LLM peut « halluciner » ?",
            ("À cause d'un bug ponctuel dans son code source",
             "Il prédit ce qui sonne vrai, pas ce qui est vrai",
             "Parce qu'il manque de RAM disponible pour répondre",
             "Parce que son alimentation électrique est instable"),
            1,
            "Toujours fact-checker les éléments importants (dates, citations, références, calculs)."),
        Question("ia-ml",
            "Quelle est la différence entre IA et machine learning ?",
            ("Aucune, c'est strictement synonyme dans le langage tech",
             "Le ML est un sous-ensemble de l'IA fondé sur les données",
             "L'IA est plus récente, le ML est plus ancien historiquement",
             "L'IA est française, le ML est américain à l'origine"),
            1,
            "IA = champ large. ML = méthode d'IA. Deep learning = sous-méthode du ML basée sur des réseaux de neurones."),
        Question("ia-data",
            "Tes échanges avec ChatGPT, ils vont où ?",
            ("Ils restent sur ton ordinateur, jamais envoyés ailleurs",
             "Ils partent sur les serveurs d'OpenAI aux États-Unis",
             "Ils sont chiffrés bout en bout, personne ne peut les lire",
             "Ils sont supprimés immédiatement après réception du message"),
            1,
            "C'est pour ça qu'on évite d'y mettre des infos perso, médicales, scolaires sensibles ou pro confidentielles."),
        Question("ia-prompt",
            "Qu'est-ce qu'un « prompt » bien formulé ?",
            ("Une question très courte sans contexte additionnel",
             "Une consigne avec contexte, rôle, format et exemples",
             "Une question rédigée en anglais et non en français",
             "Une question qui commence par « Peux-tu » poliment"),
            1,
            "Ex : « Tu es prof de maths qui explique à un lycéen. Donne 3 exemples avant la réponse. Format markdown. »"),
        Question("ia-supervised",
            "Apprentissage supervisé vs non-supervisé ?",
            ("Aucune différence, c'est exactement la même chose",
             "Supervisé = exemples étiquetés ; non-supervisé = sans labels",
             "Supervisé = manuel ; non-supervisé = automatique seulement",
             "Supervisé pour les humains, non-supervisé pour les robots"),
            1,
            "Supervisé : classifier des photos chien/chat (besoin d'exemples étiquetés). Non-supervisé : segmenter des clients en groupes sans label préalable."),
        Question("ia-cv-nlp",
            "Computer Vision vs NLP : que font-ils ?",
            ("Computer Vision pour les jeux, NLP pour les publicités",
             "CV traite images et vidéos, NLP traite le langage",
             "C'est exactement la même chose en deux noms anglais",
             "CV uniquement sur Windows, NLP uniquement sur Linux"),
            1,
            "CV : reconnaissance faciale, voitures autonomes. NLP : traduction, résumé, recherche, LLMs. Les deux convergent (modèles multi-modaux comme GPT-4 vision)."),
        Question("ia-rl",
            "Qu'est-ce que le Reinforcement Learning ?",
            ("Apprendre en lisant beaucoup de livres techniques",
             "Apprendre par essai-erreur avec récompenses et pénalités",
             "Apprendre en copiant le comportement d'autres IA",
             "Une technique réservée uniquement aux jeux d'échecs"),
            1,
            "AlphaGo, ChatGPT (le RLHF), les robots qui apprennent à marcher : tous utilisent du RL. L'agent explore, observe, ajuste."),
        Question("ia-energy",
            "L'entraînement d'un gros LLM, ça consomme :",
            ("À peu près autant qu'une recherche Google standard",
             "Énormément — équivalent de dizaines de foyers sur 1 mois",
             "Très peu, parce que tout est calculé dans le cloud léger",
             "Rien du tout — c'est de la pure magie informatique"),
            1,
            "GPT-4 a coûté ~100M$ en compute. Entraîner = très cher en énergie ; inférence (utilisation) = beaucoup moins, mais à l'échelle ça pèse aussi."),
        Question("ia-context",
            "Le « context window » d'un LLM, c'est :",
            ("La taille physique de son écran d'utilisation usuel",
             "La quantité de texte qu'il peut traiter d'un coup",
             "Le nombre d'utilisateurs qui le sollicitent en même temps",
             "La durée pendant laquelle un abonnement reste actif"),
            1,
            "Mesuré en tokens (~ 0.75 mot). GPT-4 ≈ 128k tokens (~300 pages). Au-delà, le modèle « oublie » le début. Plus c'est grand, plus c'est cher à servir."),
    ),
)

CULTURE = Theme(
    id="culture", label="Culture tech", emoji="🎓",
    questions=(
        Question("culture-linux",
            "Qui a créé Linux ?",
            ("Bill Gates en 1985 dans son garage",
             "Linus Torvalds en 1991 étudiant à Helsinki",
             "Steve Jobs en 1976 dans son garage de Cupertino",
             "Mark Zuckerberg en 2004 dans sa chambre de Harvard"),
            1,
            "Il l'a posté sur Usenet avec « it's just a hobby, won't be big and professional like GNU ». Spoiler : ça l'est devenu."),
        Question("culture-github",
            "C'est quoi GitHub ?",
            ("Un cloud de stockage comme Google Drive ou Dropbox",
             "Une plateforme d'hébergement de code basée sur Git",
             "Un réseau social fermé réservé aux développeurs",
             "Un système d'exploitation libre alternatif à Windows"),
            1,
            "Racheté par Microsoft en 2018. Alternatives : GitLab, Gitea, Forgejo, Codeberg."),
        Question("culture-docker",
            "C'est quoi un container Docker (en gros) ?",
            ("Un mini ordinateur virtuel avec un OS complet dedans",
             "Un emballage léger qui isole une appli + ses libs",
             "Un fichier compressé du type .zip ou .tar.gz",
             "Une boîte mail sécurisée pour entreprises"),
            1,
            "Le mot vient des conteneurs maritimes : standardisé, isolé, portable d'une machine à l'autre."),
        Question("culture-web",
            "L'inventeur du web, c'est qui ?",
            ("Steve Jobs au tournant des années 1980",
             "Tim Berners-Lee au CERN en 1989-90",
             "Bill Gates au début des années 1990",
             "Elon Musk au début des années 2000"),
            1,
            "Il a inventé HTTP, HTML et le concept d'URL. Le premier site web est toujours en ligne : info.cern.ch."),
        Question("culture-fdroid",
            "Qu'est-ce que F-Droid ?",
            ("Un nouvel iPhone vendu sans système Apple",
             "Un store d'apps Android 100% open source",
             "Un navigateur web léger pour smartphone",
             "Un service de streaming musical décentralisé"),
            1,
            "Apps libres, build sources publiés (traçabilité), respect de la vie privée. À installer en APK depuis f-droid.org."),
        Question("culture-ada",
            "Qui est la première programmeuse de l'histoire ?",
            ("Marie Curie au début du XXᵉ siècle française",
             "Ada Lovelace au XIXᵉ siècle anglaise",
             "Grace Hopper au milieu du XXᵉ siècle US Navy",
             "Hedy Lamarr au milieu du XXᵉ siècle actrice"),
            1,
            "Le langage Ada (utilisé en aéro et défense) est nommé en son honneur. Grace Hopper, autre figure majeure, a inventé le COBOL."),
        Question("culture-distro",
            "Linux Ubuntu, Debian, Fedora… c'est quoi exactement ?",
            ("Des concurrents commerciaux de Linux qui tournent à côté",
             "Des distributions Linux : noyau + outils, OS complet",
             "Des versions différentes de Windows depuis Vista",
             "Des navigateurs web spécialisés pour les serveurs"),
            1,
            "Le « noyau Linux » seul ne suffit pas — une distrib y ajoute shell, gestionnaire de paquets, environnement de bureau, etc."),
        Question("culture-wikipedia",
            "Wikipedia repose sur quel modèle ?",
            ("Une entreprise privée qui paie ses propres rédacteurs",
             "Une fondation à but non lucratif + bénévoles + libre",
             "L'État américain via le département de l'éducation",
             "Un algorithme d'IA qui rédige et corrige tout seul"),
            1,
            "La Wikimedia Foundation héberge, les humains rédigent. ~60M d'articles dans 300+ langues. Le contenu est sous licence Creative Commons."),
        Question("culture-python",
            "Qui a créé le langage Python ?",
            ("Linus Torvalds au début des années 1990",
             "Guido van Rossum au début des années 1990",
             "Tim Berners-Lee au début des années 1990",
             "Mark Zuckerberg au début des années 2000"),
            1,
            "Nommé d'après les Monty Python (pas le serpent !). Aujourd'hui le langage le plus utilisé au monde, notamment en data/IA."),
        Question("culture-rgpd",
            "Le RGPD, c'est :",
            ("Un protocole réseau utilisé par les data centers EU",
             "Le règlement européen sur la protection des données",
             "Un type de cryptographie asymétrique européen",
             "Un anti-spam open source européen post-2018"),
            1,
            "Donne des droits aux citoyens (accès, rectification, effacement, portabilité) et impose des obligations aux entreprises (consentement, sécurité, notification de fuite)."),
    ),
)

CRYPTO = Theme(
    id="crypto", label="Crypto & blockchain", emoji="⛓️",
    questions=(
        Question("crypto-blockchain",
            "Une blockchain, c'est quoi ?",
            ("Une base de données privée gérée par une banque",
             "Un registre partagé où chaque bloc est chaîné au précédent",
             "Un type de virus informatique propagé par les wallets",
             "Le nom d'un logiciel anti-piratage type DRM"),
            1,
            "« Bloc + chaîne » : chaque bloc contient un hash du précédent, ce qui rend la modification rétroactive quasi impossible sans refaire toute la chaîne."),
        Question("crypto-bitcoin",
            "Bitcoin a été créé par :",
            ("Elon Musk via Tesla début des années 2010",
             "Satoshi Nakamoto, pseudonyme inconnu, en 2008",
             "Mark Zuckerberg à côté de Facebook en 2009",
             "Le gouvernement américain (NSA) au tournant 2008"),
            1,
            "Le whitepaper de 2008 a posé les bases. Satoshi a disparu en 2010-2011. Personne ne sait qui c'est (théories : individu ou groupe)."),
        Question("crypto-mining",
            "Le « mining » Bitcoin consiste à :",
            ("Extraire de l'or physique au sens littéral du mot",
             "Calculer intensivement pour valider des blocs et gagner",
             "Acheter et revendre des cryptos en bourse rapidement",
             "Pirater des wallets pour récupérer des bitcoins volés"),
            1,
            "Proof-of-Work : des fermes de GPU/ASIC consomment énormément d'énergie. Une seule mine de Bitcoin = la conso d'un petit pays."),
        Question("crypto-wallet",
            "Hot wallet vs cold wallet : quelle différence ?",
            ("Le hot wallet est plus cher à l'achat que le cold",
             "Hot = en ligne et pratique ; cold = hors ligne et sûr",
             "Hot pour Bitcoin seulement, cold pour Ethereum seul",
             "Le cold wallet est obsolète et plus utilisé en 2026"),
            1,
            "Pour de gros montants, on stocke en cold (clé matérielle type Ledger, ou même papier). Pour les usages courants, hot wallet."),
        Question("crypto-hash",
            "Une fonction de hash (SHA-256 par ex.) :",
            ("Permet de chiffrer puis déchiffrer un message complet",
             "Transforme une donnée en empreinte unique de taille fixe",
             "Compresse un fichier pour le réduire avant transfert",
             "Génère un mot de passe aléatoire à chaque appel"),
            1,
            "Le hash est à sens unique. C'est ce qui permet à la blockchain de garantir l'intégrité des blocs et aux serveurs de stocker tes mdp sans les connaître."),
        Question("crypto-smart-contract",
            "Un smart contract, c'est :",
            ("Un contrat papier rédigé par un avocat moderne 2.0",
             "Un programme sur blockchain qui s'exécute tout seul",
             "Un nouveau format de fichier compressé pour contrats",
             "Une crypto-monnaie similaire à Bitcoin ou Ethereum"),
            1,
            "« Code is law » : une fois déployé, il fait ce qu'il est codé pour faire. Risque : les bugs sont quasi impossibles à corriger après coup."),
        Question("crypto-nft",
            "Un NFT (Non-Fungible Token), c'est :",
            ("Une image numérique rare et vendue très cher",
             "Un certificat unique d'appartenance sur blockchain",
             "Une crypto-monnaie au même titre que Bitcoin",
             "Un type de virus qui chiffre les fichiers image"),
            1,
            "L'image n'est pas dans la blockchain (trop lourd) — juste un pointeur + métadonnées. La propriété du token est garantie, pas l'image elle-même."),
        Question("crypto-energy",
            "Pourquoi le Bitcoin consomme autant d'énergie ?",
            ("Parce que ses serveurs sont vieux et mal optimisés",
             "Son Proof-of-Work demande des calculs intensifs constants",
             "Parce qu'il y a un nombre énorme d'utilisateurs actifs",
             "Parce que ses nœuds tournent tous sur Windows Server"),
            1,
            "Ethereum a basculé en Proof-of-Stake en 2022 (~99.95% de conso en moins). Bitcoin reste en PoW pour des raisons philosophiques + d'inertie."),
        Question("crypto-decentralized",
            "Le mot « décentralisé » pour une blockchain veut dire :",
            ("Que ça fonctionne partout dans le monde sans censure",
             "Qu'aucun acteur unique ne contrôle le réseau",
             "Que c'est gratuit d'utilisation pour les particuliers",
             "Que les transactions sont strictement anonymes"),
            1,
            "L'idée : pas besoin de faire confiance à une banque ou un État. En pratique, la concentration des nœuds/mineurs nuance ce principe."),
        Question("crypto-stablecoin",
            "Qu'est-ce qu'un stablecoin ?",
            ("Une crypto réservée aux professionnels institutionnels",
             "Une crypto dont la valeur suit un actif stable (USD…)",
             "Un wallet matériel certifié pour les pros de la finance",
             "Un protocole de paiement bancaire interbancaire moderne"),
            1,
            "USDT, USDC, DAI : généralement adossés à 1$. Servent à éviter la volatilité du marché crypto, et de pont entre fiat et crypto."),
    ),
)

OSS = Theme(
    id="oss", label="Open source & licences", emoji="🐙",
    questions=(
        Question("oss-definition",
            "Open source veut dire :",
            ("Toujours gratuit pour tous les usages possibles",
             "Code source public, modifiable, sous licence libre",
             "Disponible uniquement via la plateforme GitHub",
             "Utilisable sans aucune restriction de redistribution"),
            1,
            "Gratuit ≠ libre. Un logiciel open source peut être payant (services, support). Et un freeware peut être propriétaire."),
        Question("oss-free-vs-open",
            "« Free software » (FSF) et « open source », c'est pareil ?",
            ("Oui, deux noms strictement pour la même réalité",
             "Très proche, mais éthique (FSF) vs pragmatique (OSI)",
             "Free veut dire gratuit, open source veut dire payant",
             "Un terme est pour Linux, l'autre pour Windows uniquement"),
            1,
            "RMS (FSF) insiste sur les 4 libertés. ESR (OSI) a inventé « open source » pour rendre l'idée plus pro-business. Mêmes licences, philosophies différentes."),
        Question("oss-gpl",
            "Que veut dire la GPL (« copyleft ») ?",
            ("Le code peut être inclus dans un projet proprio sans gêne",
             "Toute dérivation doit aussi être publiée sous GPL libre",
             "Le code GPL ne peut techniquement plus être modifié du tout",
             "Le code GPL est immédiatement versé au domaine public"),
            1,
            "GPL = effet viral : si tu intègres du code GPL, ton projet entier devient GPL. C'est ce qui protège Linux et beaucoup de logiciels libres."),
        Question("oss-mit",
            "Une licence MIT (ou BSD), c'est :",
            ("Une licence strictement plus restrictive que la GPL",
             "Une licence permissive : réutilisable même en propriétaire",
             "Une licence qui interdit toute vente du logiciel dérivé",
             "Une licence réservée aux universités américaines publiques"),
            1,
            "Très populaire dans l'écosystème JavaScript. React, Tailwind, Astro… sont sous MIT. Permet aux entreprises de bâtir dessus sans contrainte."),
        Question("oss-fsf-osi",
            "Quelle est la différence entre FSF et OSI ?",
            ("Aucune, ce sont deux acronymes pour le même groupe",
             "FSF parle libertés et éthique, OSI parle dev pragmatique",
             "FSF est française et OSI est américaine essentiellement",
             "FSF est obsolète et a été remplacée par OSI en pratique"),
            1,
            "Les deux organisations approuvent souvent les mêmes licences. Mais leur communication, leur public et leur posture politique diffèrent fortement."),
        Question("oss-fork",
            "Un « fork » d'un projet, c'est :",
            ("Une cuillère utilisée comme métaphore en informatique",
             "Reprendre une copie du code pour développer à part",
             "Supprimer un projet de la plateforme d'hébergement",
             "Renommer un fichier source de manière collective"),
            1,
            "Exemples célèbres : LibreOffice (fork d'OpenOffice), MariaDB (fork de MySQL), Forgejo (fork de Gitea). Possible grâce aux licences libres."),
        Question("oss-maintainer",
            "C'est quoi un « maintainer » d'un projet open source ?",
            ("Une personne payée par une entreprise pour coder à plein temps",
             "Personne(s) qui review les PR, taggent les releases, etc.",
             "Le seul individu autorisé à écrire du code dans le repo",
             "Un utilisateur lambda qui a posé une issue ou un bug"),
            1,
            "Souvent bénévoles. Le burnout des maintainers est un vrai sujet : beaucoup de projets critiques tiennent sur 1-2 personnes (cf. xkcd 2347)."),
        Question("oss-gratuit",
            "Open source = forcément gratuit ?",
            ("Oui, c'est la définition même du terme dans la pratique",
             "Non : Red Hat, GitLab vendent du support autour du code",
             "Oui, mais uniquement sur le territoire français en pratique",
             "Cela dépend exclusivement de la licence du projet utilisée"),
            1,
            "Le modèle économique est différent : tu vends de la valeur (support, hébergement, formation) plutôt que des licences logicielles."),
        Question("oss-dco",
            "À quoi sert un DCO (Developer Certificate of Origin) ?",
            ("À identifier génétiquement le développeur via ADN",
             "À attester par « Signed-off-by » que tu as le droit",
             "À chiffrer les commits Git de bout en bout pour la sécu",
             "À donner un badge cosmétique sur le profil GitHub public"),
            1,
            "Évite que quelqu'un contribue du code non-libre (volé de son employeur par ex.). Plus léger qu'un CLA (Contributor License Agreement)."),
        Question("oss-fdroid",
            "Pourquoi F-Droid build-t-il chaque app depuis le source ?",
            ("Pour ralentir volontairement le rythme des développeurs",
             "Pour garantir que le binaire correspond bien au source",
             "Pour empêcher les copies pirates des apps populaires",
             "Pour économiser de l'espace de stockage sur le store"),
            1,
            "Cette « reproducibility » est une garantie forte que tu installes bien ce que les sources prétendent faire. Le Play Store ne donne pas cette garantie."),
    ),
)

HARDWARE = Theme(
    id="hardware", label="Hardware & low-level", emoji="🔩",
    questions=(
        Question("hw-arm-x86",
            "ARM vs x86 : quelle différence ?",
            ("ARM est plus ancien historiquement que x86 sur le marché",
             "Deux archi : ARM efficace en énergie, x86 puissant brut",
             "ARM est une marque d'antivirus pour entreprises modernes",
             "x86 fonctionne uniquement sur les OS Windows officiels"),
            1,
            "Apple Silicon (M1/M2/M3) a montré qu'ARM pouvait rivaliser avec x86 en perf desktop, à bien meilleure efficacité énergétique."),
        Question("hw-cpu-gpu",
            "CPU vs GPU : à quoi sert chacun ?",
            ("Aucune différence en pratique sur les machines modernes",
             "CPU = peu de cœurs polyvalents, GPU = milliers parallèles",
             "CPU sert aux jeux récents, GPU sert à Office et au web",
             "GPU sert juste à afficher l'image à l'écran de l'ordi"),
            1,
            "C'est pourquoi les GPU sont devenus essentiels pour l'IA : les modèles font des multiplications de matrices massivement parallélisables."),
        Question("hw-ram-disk",
            "Différence essentielle entre RAM et disque (SSD/HDD) ?",
            ("Le SSD est strictement plus rapide que la RAM moderne",
             "RAM = rapide et volatile ; disque = lent et persistant",
             "C'est exactement la même technologie sous deux noms",
             "La RAM stocke la vidéo, le disque stocke l'audio"),
            1,
            "Hiérarchie classique : registres CPU < L1/L2/L3 cache < RAM < SSD < HDD. Plus on descend, plus c'est lent mais plus grand."),
        Question("hw-bios-uefi",
            "BIOS / UEFI, c'est quoi ?",
            ("Un type de virus du secteur d'amorçage du disque dur",
             "Le firmware qui démarre la machine avant l'OS",
             "Un antivirus matériel intégré à la carte mère récente",
             "Un autre nom pour la carte mère de l'ordinateur"),
            1,
            "UEFI est le successeur moderne du BIOS (plus rapide, plus de fonctionnalités, sécurisé via Secure Boot)."),
        Question("hw-kernel-userspace",
            "Kernel space vs user space, c'est :",
            ("Deux marques de systèmes d'exploitation concurrents",
             "Noyau (matériel direct) vs applis (via appels système)",
             "Deux moitiés physiques distinctes du disque dur de l'ordi",
             "Une notion liée au framework React et au DOM virtuel"),
            1,
            "Un crash en user space tue l'appli. Un crash en kernel space → écran bleu / kernel panic. La séparation protège la stabilité du système."),
        Question("hw-driver",
            "À quoi sert un pilote (driver) ?",
            ("À faire fonctionner le navigateur web par défaut sur PC",
             "À faire l'interface entre l'OS et un matériel précis",
             "À sauvegarder automatiquement les données importantes",
             "À détecter les virus en analyse permanente en arrière-plan"),
            1,
            "Sans driver, l'OS ne sait pas parler au matériel. Linux a beaucoup de drivers intégrés au noyau, ce qui simplifie l'install."),
        Question("hw-mcu",
            "Microcontrôleur (Arduino) vs microprocesseur (CPU PC) ?",
            ("Aucune différence technique réelle entre les deux types",
             "Microcontrôleur = puce intégrée tout-en-un, peu puissante",
             "Le microcontrôleur sert dans les ordinateurs portables aussi",
             "Le microprocesseur est obsolète et plus utilisé en 2026"),
            1,
            "Idéal pour les objets connectés, robots, capteurs. Très peu d'énergie, prix dérisoires (Arduino Nano < 10€)."),
        Question("hw-bus",
            "Un bus système, dans un ordinateur, c'est :",
            ("Un véhicule de transport urbain comme métaphore informatique",
             "Un canal qui transporte les données entre composants",
             "Une marque de processeur populaire chez les développeurs",
             "Une clé USB de grande capacité avec interface rapide"),
            1,
            "Bus PCI Express, USB, SATA, I2C : autant de bus avec des protocoles et vitesses différentes selon l'usage."),
        Question("hw-clock",
            "La fréquence d'horloge d'un CPU (en GHz) indique :",
            ("La capacité totale de stockage du disque interne",
             "Le nombre de cycles par seconde (3 GHz = 3 milliards/s)",
             "La taille maximale d'écran que le CPU peut piloter",
             "Le nombre de cœurs physiques présents dans la puce"),
            1,
            "Plus haute fréquence ≠ toujours plus rapide : architecture, nombre de cœurs, cache, IPC entrent aussi en jeu."),
        Question("hw-firmware",
            "Un firmware, c'est :",
            ("Un type de mur coupe-feu matériel sécurisant un réseau",
             "Un logiciel embarqué dans le matériel pour le faire tourner",
             "Un service cloud pour héberger les sauvegardes de PC",
             "Un format de fichier compressé pour distribuer des drivers"),
            1,
            "Ton smartphone, ta box internet, ton aspirateur connecté ont tous du firmware. Les mises à jour firmware corrigent souvent des failles de sécu."),
    ),
)

IOT = Theme(
    id="iot", label="IoT & objets connectés", emoji="🏠",
    questions=(
        Question("iot-def",
            "L'« IoT » (Internet of Things), c'est :",
            ("L'internet caché et obscur réservé aux initiés",
             "Tous les objets connectés du quotidien (ampoules, etc.)",
             "Une nouvelle norme WiFi déployée à partir de 2025",
             "Un type de batterie longue durée pour objets connectés"),
            1,
            "Environ 15-30 milliards d'objets connectés en circulation en 2026. Bonus pour toi : énorme champ de sécurité offensive ET défensive."),
        Question("iot-mqtt",
            "MQTT, c'est :",
            ("Un système d'exploitation léger pour les microcontrôleurs",
             "Un protocole de messagerie léger très utilisé en IoT",
             "Une marque populaire de microcontrôleur Arduino-like",
             "Une crypto-monnaie spécialisée pour les paiements IoT"),
            1,
            "Modèle publish/subscribe : un capteur publie sur un topic (ex: `maison/salon/temperature`), tous les abonnés reçoivent. Super léger, parfait pour les petits objets."),
        Question("iot-ble",
            "BLE = Bluetooth Low Energy. C'est utile pour :",
            ("Transférer des fichiers très lourds en grande vitesse",
             "Faire tourner des objets sur pile pendant des mois",
             "Remplacer le WiFi domestique dans toute la maison",
             "Chiffrer les communications militaires sensibles"),
            1,
            "Couplé à des batteries CR2032, certains capteurs BLE durent 1-2 ans. Mais débit réduit (~1 Mbps max)."),
        Question("iot-esp32",
            "L'ESP32, c'est :",
            ("Un satellite de télécommunications grand public",
             "Un microcontrôleur ~5€ avec WiFi et Bluetooth",
             "Une version mobile d'Android pour smartphones bas-prix",
             "Un nouveau type d'écran OLED pour smartphones modernes"),
            1,
            "Successeur du célèbre ESP8266. Programmable en C, MicroPython, Arduino. Communauté gigantesque, des milliers de projets en ligne."),
        Question("iot-home-assistant",
            "Home Assistant, c'est :",
            ("Un assistant vocal proposé par Google sur Nest Hub",
             "Une plateforme open source de domotique auto-hébergée",
             "Une application de location de maisons type Airbnb",
             "Un service Microsoft qui aide à organiser ta maison"),
            1,
            "Le standard pour qui veut une maison connectée sans dépendre d'Alexa/Google. Tourne sur un Raspberry Pi à 50€."),
        Question("iot-privacy",
            "Quel est le principal risque privacy des objets connectés ?",
            ("Aucun, tout est chiffré bout en bout par défaut",
             "Beaucoup envoient tes données chez le fabricant à l'étranger",
             "Ils consomment trop d'énergie sur le réseau électrique",
             "Ils captent les ondes radio du voisinage en permanence"),
            1,
            "Caméras Xiaomi, enceintes Alexa, robots aspirateurs : la collecte est massive et opaque. Self-hosted (Home Assistant) ou Matter/local pour s'en protéger."),
        Question("iot-zigbee",
            "Z-Wave et Zigbee sont :",
            ("Des marques connues de lampes connectées bon marché",
             "Des protocoles radio bas-énergie pour la domotique",
             "Des langages de programmation pour microcontrôleurs IoT",
             "Des distributions Linux légères pour objets connectés"),
            1,
            "Maillage radio (mesh) : chaque appareil relaie. Très peu d'énergie, portée étendue. Zigbee est ouvert, Z-Wave est propriétaire."),
        Question("iot-edge",
            "Edge computing, c'est :",
            ("Faire les calculs sur le bord d'une table physiquement",
             "Faire les calculs au plus près du capteur, pas dans le cloud",
             "Une nouvelle version du cloud public lancée récemment",
             "Calculer à la limite de la batterie pour économiser"),
            1,
            "Bénéfices : latence faible, moins de bande passante consommée, données sensibles qui restent locales. Indispensable pour la voiture autonome, l'industriel temps réel."),
        Question("iot-lorawan",
            "LoRaWAN, c'est utile pour :",
            ("Faire du streaming vidéo Netflix en zone rurale isolée",
             "Envoyer de petits messages sur plusieurs km, peu de conso",
             "Remplacer totalement la 5G mobile chez les opérateurs",
             "Chiffrer le WiFi de la maison avec une clé physique"),
            1,
            "Très bas débit, très longue portée, très peu d'énergie. Modèle inverse de la 5G : pas pour streamer, pour piquer un capteur tous les quart d'heure."),
        Question("iot-default-pwd",
            "Le risque #1 de sécurité des objets connectés grand public :",
            ("Ils sont vendus trop cher pour leur qualité réelle",
             "Mots de passe par défaut jamais changés + firmware obsolète",
             "Trop d'antivirus installés en parallèle qui se gênent entre eux",
             "Ils sont devenus trop intelligents et difficiles à configurer"),
            1,
            "Le botnet Mirai (2016) a infecté 600 000 objets connectés via mdp par défaut, et a fait tomber Twitter, GitHub, etc. Le risque est très réel."),
    ),
)

CATALOG: tuple[Theme, ...] = (VOCAB, CYBER, DEV, NETWORK, IA, CULTURE, CRYPTO, OSS, HARDWARE, IOT)
BY_ID: dict[str, Theme] = {t.id: t for t in CATALOG}
TOTAL_THEMES = len(CATALOG)
